// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCehVdC-W26Jexhe2_bMZGDh3qDwk5lD7o',
    appId: '1:544016935933:web:1d129a12e8b52a9f888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    authDomain: 'laundary-app-272a6.firebaseapp.com',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBABKCxiu17PBwyDQm52jNDM7CkoOF9UxA',
    appId: '1:544016935933:android:fa51f6b9a808129c888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIE38i8tKG-MPOCc7MzL-TNKN0-imb7UY',
    appId: '1:544016935933:ios:37c9f9bb9cb84879888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIE38i8tKG-MPOCc7MzL-TNKN0-imb7UY',
    appId: '1:544016935933:ios:3ee68788a5734d1a888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCehVdC-W26Jexhe2_bMZGDh3qDwk5lD7o',
    appId: '1:544016935933:web:9113fc4dbc6535a1888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    authDomain: 'laundary-app-272a6.firebaseapp.com',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
  );

}